server:
  port: 4444

spring:  application:    name: Zuul-Proxy-Server

eureka:  client: #   eureka-server-port: 2222
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:2222/eureka/
  instance:
    hostname: localhost


zuul:
  prefix: /api  routes:    simcard-service:
      service-id: SIMCARD-SERVICE
      path: /simcard-service/**
      strip-prefix: false
    order-service:
      service-id: ORDER-SERVICE
      path: /order-service/**
      strip-prefix: false
    customer-service:
      service-id: CUSTOMER-SERVICE
      path: /customer-service/**
      strip-prefix: false    
    useroffer-service:
      service-id: USER-OFFER-SERVICE
      path: /useroffer-service/**
      strip-prefix: false  