server:
  port: 4444

spring:  application:    name: Zuul-Proxy-Server

eureka:  client: #   eureka-server-port: 2222
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:2222/eureka/
  instance:
    hostname: localhost


zuul:  routes:    customer-service:
       service-id: /customer-service/**
       path: /customer-service/**
       url: "http://CUSTOMER-SERVICE/"
       strip-prefix: false
    order-service:
      service-id: /order-service/**
      path: /order-service/**
      url: "http://ORDER-SERVICE/"
      strip-prefix: false
    simcard-service:
      service-id: /simcard-service/**
      path: /simcard-service/**
      url: "http://SIMCARD-SERVICE/"
      strip-prefix: false
    useroffer-service:
      service-id: /useroffer-service/**
      path: /useroffer-service/**
      url: "http://USER-OFFER-SERVICE/"
      strip-prefix: false   
           