eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 9000
spring:
  application:
    name: SIMCARD-SERVICE
  datasource:    username: root
    password: piyush
    url:  jdbc:mysql://localhost:3306/test?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect           